name: CI

on:
  push:
    branches: [ no-provisioning ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          fetch-depth: '0'

      - name: Set active Xcode path
        run: sudo xcode-select -s /Applications/Xcode_13.1.app/Contents/Developer

      - name: Create canonical source directory
        run: |
          set -x
          sudo mkdir /Users/telegram
          sudo chown -R $(whoami) /Users/telegram
          cp -R $GITHUB_WORKSPACE /Users/telegram/
          mv /Users/telegram/$(basename $GITHUB_WORKSPACE) /Users/telegram/telegram-ios

      - name: Build the App
        run: |
          set -x

          # source code paths are included in the final binary, so we need to make them stable across builds
          SOURCE_DIR=/Users/telegram/telegram-ios

          # use canonical bazel root
          BAZEL_USER_ROOT="/private/var/tmp/_bazel_telegram"

          # download bazel
          mkdir -p $HOME/bazel-dist
          pushd $HOME/bazel-dist
          curl -O -L https://github.com/bazelbuild/bazel/releases/download/4.0.0/bazel-4.0.0-darwin-x86_64
          mv bazel-4.0.0* bazel
          chmod +x bazel
          ./bazel --version
          popd

          cd $SOURCE_DIR

          BUILD_NUMBER_OFFSET="$(cat build_number_offset)"

          export APP_VERSION=$(cat versions.json | python3 -c 'import json,sys;obj=json.load(sys.stdin);print(obj["app"]);')
          export COMMIT_COUNT=$(git rev-list --count HEAD)
          export COMMIT_COUNT="$(($COMMIT_COUNT+$BUILD_NUMBER_OFFSET))"
          export BUILD_NUMBER="$COMMIT_COUNT"
          echo "BUILD_NUMBER=$(echo $BUILD_NUMBER)" >> $GITHUB_ENV
          echo "APP_VERSION=$(echo $APP_VERSION)" >> $GITHUB_ENV

          # prepare temporary keychain
          export MY_KEYCHAIN="temp.keychain"
          export MY_KEYCHAIN_PASSWORD="secret"
          security create-keychain -p "$MY_KEYCHAIN_PASSWORD" "$MY_KEYCHAIN"
          security list-keychains -d user -s "$MY_KEYCHAIN" $(security list-keychains -d user | sed s/\"//g)
          security set-keychain-settings "$MY_KEYCHAIN"
          security unlock-keychain -p "$MY_KEYCHAIN_PASSWORD" "$MY_KEYCHAIN"

          # install fake certificates
          export CERTS_PATH="build-system/fake-codesigning/certs/distribution"
          for f in "$CERTS_PATH"/*.p12; do
            security import "$f" -k "$MY_KEYCHAIN" -P "" -T /usr/bin/codesign -T /usr/bin/security
          done
          # fake certificates are self-signed, so we need to manually mark them as trusted (otherwise bazel will not pick them up)
          for f in "$CERTS_PATH"/*.cer; do
            sudo security add-trusted-cert -d -r trustRoot -p codeSign -k "$MY_KEYCHAIN" "$f"
          done
          security set-key-partition-list -S apple-tool:,apple: -k "$MY_KEYCHAIN_PASSWORD" "$MY_KEYCHAIN"

          # use the official release configuration
          rm -rf $HOME/telegram-configuration
          mkdir -p $HOME/telegram-configuration
          cp -R telegram-configuration-dist/* $HOME/telegram-configuration/

          # generate project without provisioning profiles
          python3 build-system/Make/Make.py \
            --bazel="$HOME/bazel-dist/bazel" \
            --cacheDir="$HOME/telegram-bazel-cache" \
            generateProject \
            --configurationPath="$HOME/telegram-configuration" \
            --disableProvisioningProfiles

          # build the app
          python3 build-system/Make/Make.py \
            --bazel="$HOME/bazel-dist/bazel" \
            --bazelUserRoot="$BAZEL_USER_ROOT" \
            --cacheDir="$HOME/telegram-bazel-cache" \
            build \
            --disableParallelSwiftmoduleGeneration \
            --configurationPath="$HOME/telegram-configuration" \
            --buildNumber=$BUILD_NUMBER \
            --configuration=release_universal

          # collect ipa
          OUTPUT_PATH="build/artifacts"
          rm -rf "$OUTPUT_PATH"
          mkdir -p "$OUTPUT_PATH"
          for f in bazel-out/applebin_ios-ios_arm*-opt-ST-*/bin/Telegram/Telegram.ipa; do
            cp "$f" $OUTPUT_PATH/
          done

          # collect dsym
          mkdir -p build/DSYMs
          for f in bazel-out/applebin_ios-ios_arm*-opt-ST-*/bin/Telegram/*.dSYM; do
            cp -R "$f" build/DSYMs/
          done
          zip -r "./$OUTPUT_PATH/Telegram.DSYMs.zip" build/DSYMs 1>/dev/null

      - name: Upload IPA
        uses: actions/upload-artifact@v2
        with:
          name: release-ipa
          path: /Users/telegram/telegram-ios/build/artifacts/Telegram.ipa

      - name: Upload DSYM
        uses: actions/upload-artifact@v2
        with:
          name: release-dsym
          path: /Users/telegram/telegram-ios/build/artifacts/Telegram.DSYMs.zip
